const fmt = (value) =>
  `\u20b9${Number(value || 0).toLocaleString("en-IN", {
    maximumFractionDigits: 0,
  })}`;

function addMessage(role, content, extraClass = "") {
  const messages = document.getElementById("messages");
  const row = document.createElement("div");
  row.className = `message ${role}`;
  row.innerHTML = `<div class="avatar">${
    role === "user" ? "You" : "AI"
  }</div><div class="bubble ${extraClass}">${content}</div>`;
  messages.appendChild(row);
  messages.scrollTop = messages.scrollHeight;
  return row.querySelector(".bubble");
}

function showToast(message) {
  const stack = document.getElementById("toasts");
  const toast = document.createElement("div");
  toast.className = "toast";
  toast.textContent = message;
  stack.appendChild(toast);
  setTimeout(() => toast.remove(), 3600);
}

function addChip(text) {
  const strip = document.getElementById("toolStrip");
  const chip = document.createElement("span");
  chip.className = "chip";
  chip.textContent = text;
  strip.prepend(chip);
  while (strip.children.length > 5) strip.lastElementChild.remove();
}

function switchTab(tabName) {
  document.querySelectorAll(".tab-btn").forEach((button) => {
    button.classList.toggle("active", button.dataset.tab === tabName);
  });
  document.querySelectorAll(".tab-panel").forEach((panel) => {
    panel.classList.toggle("active", panel.id === `tab-${tabName}`);
  });
  document.querySelectorAll("[data-tab-jump]").forEach((button) => {
    button.classList.toggle("active", button.dataset.tabJump === tabName);
  });
  renderChartsForActiveTab();
}

function activeTabName() {
  return (
    document.querySelector(".tab-panel.active")?.id?.replace("tab-", "") ||
    "chat"
  );
}

function renderChartsForActiveTab() {
  if (!AppState.dashboard) return;
  const tab = activeTabName();
  window.requestAnimationFrame(() => {
    if (tab === "dashboard") {
      drawCategoryChart(
        AppState.dashboard.analytics.category_breakdown,
        "categoryChart"
      );
    }
    if (tab === "analytics") {
      drawCategoryChart(
        AppState.dashboard.analytics.category_breakdown,
        "categoryChartLarge"
      );
    }
  });
}

function transactionMarkup(txn) {
  return `
    <div class="txn">
      <strong>${txn.recipient} · ${fmt(txn.amount)}</strong>
      <span>${txn.status} · <b class="risk-${txn.risk_level}">${
    txn.risk_level
  } risk</b> · ${txn.method}</span>
    </div>
  `;
}

function approvalMarkup(item) {
  return `
    <div class="approval-item">
      <strong>${item.recipient} · ${fmt(item.amount)}</strong>
      <span>${item.transaction_id} · ${item.reason}</span>
      <div class="approval-actions">
        <button class="ghost-btn approval-decision" data-id="${
          item.id
        }" data-decision="rejected">Reject</button>
        <button class="primary-btn approval-decision" data-id="${
          item.id
        }" data-decision="approved">Approve</button>
      </div>
    </div>
  `;
}

function saveInvoices() {
  localStorage.setItem("agentic-invoices", JSON.stringify(AppState.invoices));
}

// function addInvoice(payload) {
//   const invoice = {
//     invoice_id: payload.invoice_id,
//     client: payload.client || "Demo Client",
//     amount: Number(payload.amount || 0),
//     description:
//       payload.description || "Demo invoice generated by AI assistant",
//     status: payload.status || "generated",
//     created_at: payload.created_at || new Date().toISOString(),
//     note: payload.note || "This is a simulated invoice for demo purposes only.",
//   };
//   AppState.invoices = [
//     invoice,
//     ...AppState.invoices.filter(
//       (item) => item.invoice_id !== invoice.invoice_id
//     ),
//   ];
//   AppState.selectedInvoiceId = invoice.invoice_id;
//   saveInvoices();
//   renderInvoices();
// }
function addInvoice(payload) {
  const invoice = {
    invoice_id: payload.invoice_id,
    client: payload.client || "Demo Client",
    amount: Number(payload.amount || 0),
    description:
      payload.description || "Demo invoice generated by AI assistant",
    status: payload.status || "generated",
    created_at: payload.created_at || new Date().toISOString(),
    note: payload.note || "This is a simulated invoice for demo purposes only.",
  };

  const existingInvoices = Array.isArray(AppState.invoices)
    ? AppState.invoices
    : [];

  AppState.invoices = [
    invoice,
    ...existingInvoices.filter(
      (item) => item.invoice_id !== invoice.invoice_id
    ),
  ];

  AppState.selectedInvoiceId = invoice.invoice_id;

  saveInvoices();
  renderInvoices();
}

function selectedInvoice() {
  return (
    AppState.invoices.find(
      (item) => item.invoice_id === AppState.selectedInvoiceId
    ) || AppState.invoices[0]
  );
}

function renderInvoices() {
  const list = document.getElementById("invoiceList");
  const preview = document.getElementById("invoicePreview");
  if (!list || !preview) return;

  const invoices = Array.isArray(AppState?.invoices) ? AppState.invoices : [];
  if (!invoices.length) {
    list.innerHTML = `<div class="invoice-empty"><strong>No invoices yet</strong><span>Generate one from chat, for example: Generate invoice for INR 3500 to Acme Labs.</span></div>`;
    preview.innerHTML = `<div class="invoice-paper empty-preview"><strong>Invoice preview</strong><span>Your next simulated invoice will appear here.</span></div>`;
    return;
  }

  const active = selectedInvoice();
  AppState.selectedInvoiceId = active.invoice_id;
  list.innerHTML = AppState.invoices
    .map(
      (invoice) => `
    <div class="invoice-card ${
      invoice.invoice_id === active.invoice_id ? "active" : ""
    }">
      <div>
        <strong>${invoice.invoice_id}</strong>
        <span>${invoice.client} · ${fmt(invoice.amount)} · ${
        invoice.status
      }</span>
      </div>
      <div class="invoice-actions">
        <button class="ghost-btn invoice-preview-btn" data-invoice-id="${
          invoice.invoice_id
        }">Preview</button>
        <button class="ghost-btn invoice-copy-btn" data-invoice-id="${
          invoice.invoice_id
        }">Copy ID</button>
        <button class="primary-btn invoice-sent-btn" data-invoice-id="${
          invoice.invoice_id
        }">Mark Sent</button>
      </div>
    </div>
  `
    )
    .join("");

  preview.innerHTML = `
    <div class="invoice-paper">
      <div class="invoice-paper-head">
        <div><span>Demo Invoice</span><strong>${
          active.invoice_id
        }</strong></div>
        <em>${active.status}</em>
      </div>
      <div class="invoice-meta">
        <span>Bill to</span>
        <strong>${active.client}</strong>
        <span>Created</span>
        <strong>${new Date(active.created_at).toLocaleString()}</strong>
      </div>
      <div class="invoice-line">
        <span>${active.description}</span>
        <strong>${fmt(active.amount)}</strong>
      </div>
      <div class="invoice-total">
        <span>Total due</span>
        <strong>${fmt(active.amount)}</strong>
      </div>
      <p>${active.note}</p>
      <small>No real invoice, tax document, or payment request was issued.</small>
    </div>
  `;
  bindInvoiceButtons();
}

function bindInvoiceButtons() {
  document.querySelectorAll(".invoice-preview-btn").forEach((button) => {
    button.addEventListener("click", () => {
      AppState.selectedInvoiceId = button.dataset.invoiceId;
      renderInvoices();
    });
  });
  document.querySelectorAll(".invoice-copy-btn").forEach((button) => {
    button.addEventListener("click", async () => {
      await navigator.clipboard?.writeText(button.dataset.invoiceId);
      showToast(`Copied ${button.dataset.invoiceId}`);
    });
  });
  document.querySelectorAll(".invoice-sent-btn").forEach((button) => {
    button.addEventListener("click", () => {
      AppState.invoices = AppState.invoices.map((invoice) =>
        invoice.invoice_id === button.dataset.invoiceId
          ? { ...invoice, status: "sent" }
          : invoice
      );
      saveInvoices();
      renderInvoices();
      showToast("Invoice marked sent in demo mode");
    });
  });
}

function bindApprovalButtons() {
  document.querySelectorAll(".approval-decision").forEach((button) => {
    button.addEventListener("click", async () => {
      await API.decideApproval(button.dataset.id, button.dataset.decision);
      showToast(`Approval ${button.dataset.decision}`);
      await refreshDashboard();
    });
  });
}

function addApprovalQueueCard(payload) {
  const amount = fmt(payload.amount || 0);
  const recipient = payload.recipient || "Unknown recipient";
  const reason = payload.reason || "Risk policy triggered.";
  const bubble = addMessage(
    "assistant",
    `<strong>This simulated payment was paused and added to the approval queue.</strong><span>${amount} to ${recipient}. ${reason}</span><button class="queue-link" data-tab-target="approvals">View in Approvals</button>`,
    "approval-card"
  );
  const link = bubble.querySelector("[data-tab-target]");
  if (link) {
    link.addEventListener("click", () => switchTab("approvals"));
  }
}

// function renderDashboard(data) {
//   AppState.dashboard = data;
//   document.getElementById("walletBalance").textContent = fmt(
//     data.wallet.balance
//   );
//   document.getElementById("chatWalletBalance").textContent = fmt(
//     data.wallet.balance
//   );
//   document.getElementById("walletMini").textContent = fmt(data.wallet.balance);
//   document.getElementById("walletCurrency").textContent = data.wallet.currency;
//   document.getElementById("monthlySpend").textContent = fmt(
//     data.analytics.total_spend
//   );
//   document.getElementById("approvalCount").textContent = data.approvals.length;
//   document.getElementById("chatApprovalCount").textContent =
//     data.approvals.length;
//   document.getElementById("approvalPanelCount").textContent =
//     data.approvals.length;
//   document.getElementById("txnCount").textContent = data.transactions.length;

//   const emptyApprovals = `<div class="approval-item"><strong>No pending approvals</strong><span>Risky simulated transfers will appear here.</span></div>`;
//   const approvals = data.approvals.length
//     ? data.approvals.map(approvalMarkup).join("")
//     : emptyApprovals;
//   document.getElementById("approvalList").innerHTML = approvals;
//   document.getElementById("approvalListFull").innerHTML = approvals;

//   const emptyTransactions = `<div class="txn"><strong>No transactions yet</strong><span>Simulated payments will appear here.</span></div>`;
//   const transactions = data.transactions.length
//     ? data.transactions.map(transactionMarkup).join("")
//     : emptyTransactions;
//   document.getElementById("transactions").innerHTML = transactions;
//   document.getElementById("transactionsFull").innerHTML = transactions;

//   document.getElementById("activityLog").innerHTML = data.logs.length
//     ? data.logs
//         .map(
//           (log) => `
//     <div class="log-row">
//       <strong>${log.type.replaceAll("_", " ")}</strong>
//       <span>${log.message}</span>
//     </div>
//   `
//         )
//         .join("")
//     : `<div class="log-row"><strong>No activity yet</strong><span>Agent and audit events will appear here.</span></div>`;

//   document.getElementById("recommendations").innerHTML =
//     data.analytics.recommendations
//       .map(
//         (item) => `
//     <div class="recommendation"><strong>Recommendation</strong><span>${item}</span></div>
//   `
//       )
//       .join("");

//   document.getElementById("fraudInsights").innerHTML = data.analytics
//     .fraud_insights.length
//     ? data.analytics.fraud_insights
//         .map(
//           (item) => `
//     <div class="txn">
//       <strong>${item.recipient}</strong>
//       <span>${item.transaction_id} · <b class="risk-${item.risk_level}">${item.risk_level} risk</b></span>
//     </div>
//   `
//         )
//         .join("")
//     : `<div class="txn"><strong>No active fraud insights</strong><span>High-risk simulated transfers will appear here.</span></div>`;

//   bindApprovalButtons();
//   renderInvoices();
//   renderChartsForActiveTab();
//   if (data.approvals[0]) {
//     AppState.currentApproval = data.approvals[0];
//   }
// }
function renderDashboard(data) {
  AppState.dashboard = data || {};

  const wallet = data?.wallet || {};
  const analytics = data?.analytics || {};

  const approvals = Array.isArray(data?.approvals) ? data.approvals : [];

  const transactions = Array.isArray(data?.transactions)
    ? data.transactions
    : [];

  const logs = Array.isArray(data?.logs) ? data.logs : [];

  const recommendations = Array.isArray(analytics?.recommendations)
    ? analytics.recommendations
    : [];

  const fraudInsights = Array.isArray(analytics?.fraud_insights)
    ? analytics.fraud_insights
    : [];

  document.getElementById("walletBalance").textContent = fmt(wallet.balance);

  document.getElementById("chatWalletBalance").textContent = fmt(
    wallet.balance
  );

  document.getElementById("walletMini").textContent = fmt(wallet.balance);

  document.getElementById("walletCurrency").textContent =
    wallet.currency || "INR";

  document.getElementById("monthlySpend").textContent = fmt(
    analytics.total_spend
  );

  document.getElementById("approvalCount").textContent = approvals.length;

  document.getElementById("chatApprovalCount").textContent = approvals.length;

  document.getElementById("approvalPanelCount").textContent = approvals.length;

  document.getElementById("txnCount").textContent = transactions.length;

  const emptyApprovals = `
    <div class="approval-item">
      <strong>No pending approvals</strong>
      <span>Risky simulated transfers will appear here.</span>
    </div>
  `;

  document.getElementById("approvalList").innerHTML = approvals.length
    ? approvals.map(approvalMarkup).join("")
    : emptyApprovals;

  document.getElementById("approvalListFull").innerHTML = approvals.length
    ? approvals.map(approvalMarkup).join("")
    : emptyApprovals;

  const emptyTransactions = `
    <div class="txn">
      <strong>No transactions yet</strong>
      <span>Simulated payments will appear here.</span>
    </div>
  `;

  document.getElementById("transactions").innerHTML = transactions.length
    ? transactions.map(transactionMarkup).join("")
    : emptyTransactions;

  document.getElementById("transactionsFull").innerHTML = transactions.length
    ? transactions.map(transactionMarkup).join("")
    : emptyTransactions;

  document.getElementById("activityLog").innerHTML = logs.length
    ? logs
        .map(
          (log) => `
            <div class="log-row">
              <strong>${String(log.type || "").replaceAll("_", " ")}</strong>
              <span>${log.message || ""}</span>
            </div>
          `
        )
        .join("")
    : `
        <div class="log-row">
          <strong>No activity yet</strong>
          <span>Agent and audit events will appear here.</span>
        </div>
      `;

  document.getElementById("recommendations").innerHTML = recommendations.length
    ? recommendations
        .map(
          (item) => `
            <div class="recommendation">
              <strong>Recommendation</strong>
              <span>${item}</span>
            </div>
          `
        )
        .join("")
    : `
        <div class="recommendation">
          <strong>No recommendations</strong>
          <span>AI insights will appear here.</span>
        </div>
      `;

  document.getElementById("fraudInsights").innerHTML = fraudInsights.length
    ? fraudInsights
        .map(
          (item) => `
            <div class="txn">
              <strong>${item.recipient}</strong>
              <span>
                ${item.transaction_id}
                ·
                <b class="risk-${item.risk_level}">
                  ${item.risk_level} risk
                </b>
              </span>
            </div>
          `
        )
        .join("")
    : `
        <div class="txn">
          <strong>No active fraud insights</strong>
          <span>High-risk simulated transfers will appear here.</span>
        </div>
      `;

  bindApprovalButtons();
  renderInvoices();
  renderChartsForActiveTab();

  AppState.currentApproval = approvals.length > 0 ? approvals[0] : null;
}

function openTopUpModal(amount = "") {
  const modal = document.getElementById("topUpModal");
  document.getElementById("topUpAmount").value = amount;
  document.querySelectorAll(".preset-btn").forEach((button) => {
    button.classList.toggle("active", button.dataset.amount === String(amount));
  });
  if (!modal.open) modal.showModal();
}

async function submitTopUp(amount, source = "ui") {
  const numeric = Number(amount);
  if (!Number.isFinite(numeric) || numeric <= 0) {
    showToast("Enter a valid top-up amount");
    return;
  }
  await API.topUpWallet(AppState.sessionId, numeric, source);
  document.getElementById("topUpModal").close();
  showToast(`Added ${fmt(numeric)} to demo wallet`);
  await refreshDashboard();
}

async function refreshDashboard() {
  const data = await API.dashboard(AppState.sessionId);
  renderDashboard(data);
}
